# this is a toml configuration file https://toml.io/
cluster_id = "2Profs"

[network]
ssid =  "" 
wifi_password = ''
broker="home-broker.local"  # or where ever your MQTT broker is

[email]
to_list = ["foo@bar.com", "bar@foo.com"]
gmail_password = ""
gmail_user = ""

[sensor]
#  do not use shashes "/" in the names. It messes with the MQTT wild cards
#  email = true means that the sensor sends emails when sensors lost and found
[sensor.1]
name = "Big Generator"
email = true
[sensor.2]
name = "Utility power company"
email = true
[sensor.3]
name = "solar_batteries"
email = false

