
# NOTE mqtt_cfg.py import is generated by this file, install.py
# it must drop a python3 compatable file that is imported in the system
# so make changes here
#

ssid = 'JEDguest'
wifi_pw = '9098673852'
server = 'home-broker.local'   # or whate ever your broker name is
